; Auto-generated. Do not edit!


(cl:in-package iai_control_msgs-msg)


;//! \htmlinclude PTUResult.msg.html

(cl:defclass <PTUResult> (roslisp-msg-protocol:ros-message)
  ((answer
    :reader answer
    :initarg :answer
    :type cl:string
    :initform ""))
)

(cl:defclass PTUResult (<PTUResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PTUResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PTUResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name iai_control_msgs-msg:<PTUResult> is deprecated: use iai_control_msgs-msg:PTUResult instead.")))

(cl:ensure-generic-function 'answer-val :lambda-list '(m))
(cl:defmethod answer-val ((m <PTUResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader iai_control_msgs-msg:answer-val is deprecated.  Use iai_control_msgs-msg:answer instead.")
  (answer m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PTUResult>) ostream)
  "Serializes a message object of type '<PTUResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'answer))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'answer))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PTUResult>) istream)
  "Deserializes a message object of type '<PTUResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'answer) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'answer) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PTUResult>)))
  "Returns string type for a message object of type '<PTUResult>"
  "iai_control_msgs/PTUResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PTUResult)))
  "Returns string type for a message object of type 'PTUResult"
  "iai_control_msgs/PTUResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PTUResult>)))
  "Returns md5sum for a message object of type '<PTUResult>"
  "d7e708f879c94bb931716d8f4f130f30")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PTUResult)))
  "Returns md5sum for a message object of type 'PTUResult"
  "d7e708f879c94bb931716d8f4f130f30")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PTUResult>)))
  "Returns full string definition for message of type '<PTUResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string answer~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PTUResult)))
  "Returns full string definition for message of type 'PTUResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%string answer~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PTUResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'answer))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PTUResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PTUResult
    (cl:cons ':answer (answer msg))
))
