// Generated by gencpp from file rosprolog/JSONWrapperRequest.msg
// DO NOT EDIT!


#ifndef ROSPROLOG_MESSAGE_JSONWRAPPERREQUEST_H
#define ROSPROLOG_MESSAGE_JSONWRAPPERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosprolog
{
template <class ContainerAllocator>
struct JSONWrapperRequest_
{
  typedef JSONWrapperRequest_<ContainerAllocator> Type;

  JSONWrapperRequest_()
    : mode()
    , json_data()  {
    }
  JSONWrapperRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , json_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _json_data_type;
  _json_data_type json_data;





  typedef boost::shared_ptr< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JSONWrapperRequest_

typedef ::rosprolog::JSONWrapperRequest_<std::allocator<void> > JSONWrapperRequest;

typedef boost::shared_ptr< ::rosprolog::JSONWrapperRequest > JSONWrapperRequestPtr;
typedef boost::shared_ptr< ::rosprolog::JSONWrapperRequest const> JSONWrapperRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosprolog::JSONWrapperRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosprolog::JSONWrapperRequest_<ContainerAllocator1> & lhs, const ::rosprolog::JSONWrapperRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.json_data == rhs.json_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosprolog::JSONWrapperRequest_<ContainerAllocator1> & lhs, const ::rosprolog::JSONWrapperRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosprolog

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "600c5764c78cd158a89a10ca5449bf63";
  }

  static const char* value(const ::rosprolog::JSONWrapperRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x600c5764c78cd158ULL;
  static const uint64_t static_value2 = 0xa89a10ca5449bf63ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosprolog/JSONWrapperRequest";
  }

  static const char* value(const ::rosprolog::JSONWrapperRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode\n"
"string json_data\n"
;
  }

  static const char* value(const ::rosprolog::JSONWrapperRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.json_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JSONWrapperRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosprolog::JSONWrapperRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosprolog::JSONWrapperRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
    s << indent << "json_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.json_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSPROLOG_MESSAGE_JSONWRAPPERREQUEST_H
