(cl:defpackage attache_msgs-srv
  (:use )
  (:export
   "ATTACHMENT"
   "<ATTACHMENT-REQUEST>"
   "ATTACHMENT-REQUEST"
   "<ATTACHMENT-RESPONSE>"
   "ATTACHMENT-RESPONSE"
   "JOINTCONTROL"
   "<JOINTCONTROL-REQUEST>"
   "JOINTCONTROL-REQUEST"
   "<JOINTCONTROL-RESPONSE>"
   "JOINTCONTROL-RESPONSE"
   "JOINTINFORMATION"
   "<JOINTINFORMATION-REQUEST>"
   "JOINTINFORMATION-REQUEST"
   "<JOINTINFORMATION-RESPONSE>"
   "JOINTINFORMATION-RESPONSE"
  ))

