// Generated by gencpp from file json_prolog_msgs/PrologFinish.msg
// DO NOT EDIT!


#ifndef JSON_PROLOG_MSGS_MESSAGE_PROLOGFINISH_H
#define JSON_PROLOG_MSGS_MESSAGE_PROLOGFINISH_H

#include <ros/service_traits.h>


#include <json_prolog_msgs/PrologFinishRequest.h>
#include <json_prolog_msgs/PrologFinishResponse.h>


namespace json_prolog_msgs
{

struct PrologFinish
{

typedef PrologFinishRequest Request;
typedef PrologFinishResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PrologFinish
} // namespace json_prolog_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::json_prolog_msgs::PrologFinish > {
  static const char* value()
  {
    return "bbfcda76036ebbe3d36caf7af80b260c";
  }

  static const char* value(const ::json_prolog_msgs::PrologFinish&) { return value(); }
};

template<>
struct DataType< ::json_prolog_msgs::PrologFinish > {
  static const char* value()
  {
    return "json_prolog_msgs/PrologFinish";
  }

  static const char* value(const ::json_prolog_msgs::PrologFinish&) { return value(); }
};


// service_traits::MD5Sum< ::json_prolog_msgs::PrologFinishRequest> should match
// service_traits::MD5Sum< ::json_prolog_msgs::PrologFinish >
template<>
struct MD5Sum< ::json_prolog_msgs::PrologFinishRequest>
{
  static const char* value()
  {
    return MD5Sum< ::json_prolog_msgs::PrologFinish >::value();
  }
  static const char* value(const ::json_prolog_msgs::PrologFinishRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::json_prolog_msgs::PrologFinishRequest> should match
// service_traits::DataType< ::json_prolog_msgs::PrologFinish >
template<>
struct DataType< ::json_prolog_msgs::PrologFinishRequest>
{
  static const char* value()
  {
    return DataType< ::json_prolog_msgs::PrologFinish >::value();
  }
  static const char* value(const ::json_prolog_msgs::PrologFinishRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::json_prolog_msgs::PrologFinishResponse> should match
// service_traits::MD5Sum< ::json_prolog_msgs::PrologFinish >
template<>
struct MD5Sum< ::json_prolog_msgs::PrologFinishResponse>
{
  static const char* value()
  {
    return MD5Sum< ::json_prolog_msgs::PrologFinish >::value();
  }
  static const char* value(const ::json_prolog_msgs::PrologFinishResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::json_prolog_msgs::PrologFinishResponse> should match
// service_traits::DataType< ::json_prolog_msgs::PrologFinish >
template<>
struct DataType< ::json_prolog_msgs::PrologFinishResponse>
{
  static const char* value()
  {
    return DataType< ::json_prolog_msgs::PrologFinish >::value();
  }
  static const char* value(const ::json_prolog_msgs::PrologFinishResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSON_PROLOG_MSGS_MESSAGE_PROLOGFINISH_H
