(cl:defpackage designator_integration_msgs-srv
  (:use )
  (:export
   "DESIGNATORCOMMUNICATION"
   "<DESIGNATORCOMMUNICATION-REQUEST>"
   "DESIGNATORCOMMUNICATION-REQUEST"
   "<DESIGNATORCOMMUNICATION-RESPONSE>"
   "DESIGNATORCOMMUNICATION-RESPONSE"
  ))

