// Generated by gencpp from file iai_wsg_50_msgs/Cmd.msg
// DO NOT EDIT!


#ifndef IAI_WSG_50_MSGS_MESSAGE_CMD_H
#define IAI_WSG_50_MSGS_MESSAGE_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iai_wsg_50_msgs
{
template <class ContainerAllocator>
struct Cmd_
{
  typedef Cmd_<ContainerAllocator> Type;

  Cmd_()
    : mode()
    , pos(0.0)
    , speed(0.0)  {
    }
  Cmd_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , pos(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;

   typedef float _pos_type;
  _pos_type pos;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> const> ConstPtr;

}; // struct Cmd_

typedef ::iai_wsg_50_msgs::Cmd_<std::allocator<void> > Cmd;

typedef boost::shared_ptr< ::iai_wsg_50_msgs::Cmd > CmdPtr;
typedef boost::shared_ptr< ::iai_wsg_50_msgs::Cmd const> CmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iai_wsg_50_msgs::Cmd_<ContainerAllocator1> & lhs, const ::iai_wsg_50_msgs::Cmd_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.pos == rhs.pos &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iai_wsg_50_msgs::Cmd_<ContainerAllocator1> & lhs, const ::iai_wsg_50_msgs::Cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iai_wsg_50_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9d4654d92a2e086717420189f98c76a";
  }

  static const char* value(const ::iai_wsg_50_msgs::Cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9d4654d92a2e086ULL;
  static const uint64_t static_value2 = 0x717420189f98c76aULL;
};

template<class ContainerAllocator>
struct DataType< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iai_wsg_50_msgs/Cmd";
  }

  static const char* value(const ::iai_wsg_50_msgs::Cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode\n"
"float32 pos\n"
"float32 speed\n"
"\n"
;
  }

  static const char* value(const ::iai_wsg_50_msgs::Cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.pos);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iai_wsg_50_msgs::Cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iai_wsg_50_msgs::Cmd_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
    s << indent << "pos: ";
    Printer<float>::stream(s, indent + "  ", v.pos);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAI_WSG_50_MSGS_MESSAGE_CMD_H
