// Generated by gencpp from file iai_wsg_50_msgs/IncrResponse.msg
// DO NOT EDIT!


#ifndef IAI_WSG_50_MSGS_MESSAGE_INCRRESPONSE_H
#define IAI_WSG_50_MSGS_MESSAGE_INCRRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iai_wsg_50_msgs
{
template <class ContainerAllocator>
struct IncrResponse_
{
  typedef IncrResponse_<ContainerAllocator> Type;

  IncrResponse_()
    : error(0)  {
    }
  IncrResponse_(const ContainerAllocator& _alloc)
    : error(0)  {
  (void)_alloc;
    }



   typedef uint8_t _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IncrResponse_

typedef ::iai_wsg_50_msgs::IncrResponse_<std::allocator<void> > IncrResponse;

typedef boost::shared_ptr< ::iai_wsg_50_msgs::IncrResponse > IncrResponsePtr;
typedef boost::shared_ptr< ::iai_wsg_50_msgs::IncrResponse const> IncrResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator1> & lhs, const ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator2> & rhs)
{
  return lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator1> & lhs, const ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iai_wsg_50_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf8e3bc5443691736455ca47e3128027";
  }

  static const char* value(const ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf8e3bc544369173ULL;
  static const uint64_t static_value2 = 0x6455ca47e3128027ULL;
};

template<class ContainerAllocator>
struct DataType< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iai_wsg_50_msgs/IncrResponse";
  }

  static const char* value(const ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 error\n"
"\n"
;
  }

  static const char* value(const ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IncrResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iai_wsg_50_msgs::IncrResponse_<ContainerAllocator>& v)
  {
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAI_WSG_50_MSGS_MESSAGE_INCRRESPONSE_H
