// Generated by gencpp from file iai_wsg_50_msgs/SpeedCmd.msg
// DO NOT EDIT!


#ifndef IAI_WSG_50_MSGS_MESSAGE_SPEEDCMD_H
#define IAI_WSG_50_MSGS_MESSAGE_SPEEDCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iai_wsg_50_msgs
{
template <class ContainerAllocator>
struct SpeedCmd_
{
  typedef SpeedCmd_<ContainerAllocator> Type;

  SpeedCmd_()
    : speed(0.0)
    , force(0.0)  {
    }
  SpeedCmd_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , force(0.0)  {
  (void)_alloc;
    }



   typedef float _speed_type;
  _speed_type speed;

   typedef float _force_type;
  _force_type force;





  typedef boost::shared_ptr< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> const> ConstPtr;

}; // struct SpeedCmd_

typedef ::iai_wsg_50_msgs::SpeedCmd_<std::allocator<void> > SpeedCmd;

typedef boost::shared_ptr< ::iai_wsg_50_msgs::SpeedCmd > SpeedCmdPtr;
typedef boost::shared_ptr< ::iai_wsg_50_msgs::SpeedCmd const> SpeedCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator1> & lhs, const ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.force == rhs.force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator1> & lhs, const ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iai_wsg_50_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78bc8e5b0b23e68f9c42fc33214123d4";
  }

  static const char* value(const ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78bc8e5b0b23e68fULL;
  static const uint64_t static_value2 = 0x9c42fc33214123d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iai_wsg_50_msgs/SpeedCmd";
  }

  static const char* value(const ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 speed\n"
"float32 force\n"
;
  }

  static const char* value(const ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeedCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iai_wsg_50_msgs::SpeedCmd_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "force: ";
    Printer<float>::stream(s, indent + "  ", v.force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAI_WSG_50_MSGS_MESSAGE_SPEEDCMD_H
