// Generated by gencpp from file iai_control_msgs/MultiJointVelocityCommand.msg
// DO NOT EDIT!


#ifndef IAI_CONTROL_MSGS_MESSAGE_MULTIJOINTVELOCITYCOMMAND_H
#define IAI_CONTROL_MSGS_MESSAGE_MULTIJOINTVELOCITYCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace iai_control_msgs
{
template <class ContainerAllocator>
struct MultiJointVelocityCommand_
{
  typedef MultiJointVelocityCommand_<ContainerAllocator> Type;

  MultiJointVelocityCommand_()
    : header()
    , velocity()  {
    }
  MultiJointVelocityCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MultiJointVelocityCommand_

typedef ::iai_control_msgs::MultiJointVelocityCommand_<std::allocator<void> > MultiJointVelocityCommand;

typedef boost::shared_ptr< ::iai_control_msgs::MultiJointVelocityCommand > MultiJointVelocityCommandPtr;
typedef boost::shared_ptr< ::iai_control_msgs::MultiJointVelocityCommand const> MultiJointVelocityCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator1> & lhs, const ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator1> & lhs, const ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iai_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2d712284996c67e9ebdac0d389fff20";
  }

  static const char* value(const ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2d712284996c67eULL;
  static const uint64_t static_value2 = 0x9ebdac0d389fff20ULL;
};

template<class ContainerAllocator>
struct DataType< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iai_control_msgs/MultiJointVelocityCommand";
  }

  static const char* value(const ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Command to move a set of velocity-resolved robot joints \n"
"float32[] velocity     #joint velocity in rad/s\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiJointVelocityCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iai_control_msgs::MultiJointVelocityCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAI_CONTROL_MSGS_MESSAGE_MULTIJOINTVELOCITYCOMMAND_H
